# Generated by Django 4.1 on 2022-08-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='collector',
            name='website',
        ),
    ]
