# Generated by Django 4.1 on 2022-08-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_website_remove_collector_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='collector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.collector'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='type',
            field=models.CharField(choices=[('G', 'github'), ('D', 'deployed')], default='G', max_length=1),
        ),
    ]
